# Generated by Django 4.2.7 on 2026-08-11 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0008_llmmodelconfig_embedding_dimension_and_more'),
        ('requirements', '0012_requirementintegrationdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='知识编码')),
                ('category', models.CharField(choices=[('term', '术语'), ('role_permission', '角色权限'), ('module_boundary', '模块边界'), ('business_rule', '业务规则'), ('business_flow', '业务流程'), ('non_functional', '非功能约束'), ('external_dependency', '外部依赖')], max_length=30, verbose_name='知识类别')),
                ('title', models.CharField(max_length=200, verbose_name='知识标题')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('active', '有效'), ('retired', '已失效')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_knowledge_items',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, verbose_name='模块编码')),
                ('name', models.CharField(max_length=120, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='模块说明')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='project_knowledge.projectmodule', verbose_name='上级模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_modules', to='configuration.projectconfig', verbose_name='项目')),
            ],
            options={
                'db_table': 'project_modules',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModuleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120, verbose_name='别名')),
                ('normalized_alias', models.CharField(max_length=120, verbose_name='归一化别名')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='project_knowledge.projectmodule', verbose_name='模块')),
            ],
            options={
                'db_table': 'project_module_aliases',
            },
        ),
        migrations.CreateModel(
            name='ProjectKnowledgeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='修订号')),
                ('title', models.CharField(max_length=200, verbose_name='标题快照')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('status', models.CharField(choices=[('candidate', '待确认'), ('conflict', '有冲突'), ('confirmed', '已确认'), ('superseded', '已替代'), ('retired', '已失效'), ('rejected', '已拒绝')], default='candidate', max_length=20, verbose_name='状态')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='提取模型')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_knowledge_revisions', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_revisions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('effective_from_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='effective_knowledge_revisions', to='requirements.requirementversion', verbose_name='生效版本')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='project_knowledge.projectknowledgeitem', verbose_name='知识项')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='project_knowledge.projectknowledgerevision', verbose_name='前一修订')),
            ],
            options={
                'db_table': 'project_knowledge_revisions',
                'ordering': ['-revision_no', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectknowledgeitem',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_items', to='project_knowledge.projectmodule', verbose_name='适用模块'),
        ),
        migrations.AddField(
            model_name='projectknowledgeitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='configuration.projectconfig', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='ProjectKnowledgeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=40, verbose_name='来源类型')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='来源ID')),
                ('source_revision_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='来源修订ID')),
                ('source_locator', models.CharField(blank=True, max_length=255, verbose_name='来源位置')),
                ('excerpt', models.TextField(verbose_name='证据快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='project_knowledge.projectknowledgerevision', verbose_name='知识修订')),
            ],
            options={
                'db_table': 'project_knowledge_evidence',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_ids', models.JSONField(blank=True, default=list, verbose_name='来源文档ID')),
                ('include_confirmed_requirements', models.BooleanField(default=True, verbose_name='包含已确认需求')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('partial_success', '部分成功'), ('failed', '失败')], default='pending', max_length=24, verbose_name='状态')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='候选数')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='模型')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_extraction_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_extraction_runs', to='configuration.projectconfig', verbose_name='项目')),
            ],
            options={
                'db_table': 'knowledge_extraction_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmodulealias',
            constraint=models.UniqueConstraint(fields=('module', 'normalized_alias'), name='uniq_module_normalized_alias'),
        ),
        migrations.AddConstraint(
            model_name='projectmodule',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_project_module_code'),
        ),
        migrations.AddConstraint(
            model_name='projectknowledgerevision',
            constraint=models.UniqueConstraint(fields=('item', 'revision_no'), name='uniq_knowledge_revision_no'),
        ),
        migrations.AddConstraint(
            model_name='projectknowledgeitem',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='uniq_project_knowledge_code'),
        ),
    ]
