# Generated by Django 4.2.7 on 2026-08-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def seed_module_revisions(apps, schema_editor):
    ProjectModule = apps.get_model('project_knowledge', 'ProjectModule')
    ProjectModuleRevision = apps.get_model('project_knowledge', 'ProjectModuleRevision')
    for module in ProjectModule.objects.all().iterator():
        ProjectModuleRevision.objects.create(
            module_id=module.id,
            revision_no=1,
            parent_id=module.parent_id,
            code=module.code,
            name=module.name,
            description=module.description,
            module_status=module.status,
            sort_order=module.sort_order,
            status='confirmed',
            confirmed_at=timezone.now(),
        )


def remove_module_revisions(apps, schema_editor):
    apps.get_model('project_knowledge', 'ProjectModuleRevision').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModuleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='修订号')),
                ('code', models.SlugField(max_length=80, verbose_name='模块编码')),
                ('name', models.CharField(max_length=120, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='模块说明')),
                ('module_status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='模块状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('candidate', '待确认'), ('confirmed', '已确认'), ('superseded', '已替代')], default='candidate', max_length=20, verbose_name='修订状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_project_module_revisions', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_module_revisions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='project_knowledge.projectmodule', verbose_name='模块')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_child_revisions', to='project_knowledge.projectmodule', verbose_name='上级模块')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='project_knowledge.projectmodulerevision', verbose_name='前一修订')),
            ],
            options={
                'db_table': 'project_module_revisions',
                'ordering': ['-revision_no', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmodulerevision',
            constraint=models.UniqueConstraint(fields=('module', 'revision_no'), name='uniq_project_module_revision_no'),
        ),
        migrations.RunPython(seed_module_revisions, remove_module_revisions),
    ]
