# Generated by Django 4.2.7 on 2026-08-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_knowledge', '0002_projectmodulerevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeextractionrun',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='knowledgeextractionrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='project_knowledge.knowledgeextractionrun', verbose_name='重试来源'),
        ),
    ]
