# Generated by Django 4.2.7 on 2026-08-11 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0008_llmmodelconfig_embedding_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=40, verbose_name='资产类型')),
                ('asset_id', models.PositiveBigIntegerField(verbose_name='资产ID')),
                ('revision_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='修订ID')),
                ('action', models.CharField(choices=[('upsert', '写入'), ('delete', '删除'), ('rebuild', '重建')], default='upsert', max_length=20, verbose_name='动作')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='内容哈希')),
                ('target_index', models.CharField(blank=True, max_length=160, verbose_name='目标索引')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index_jobs', to='configuration.projectconfig', verbose_name='项目')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_search_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'db_table': 'search_index_jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='search_job_status_idx')],
            },
        ),
    ]
