# Generated by Django 4.2.7 on 2026-08-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectimportbatch',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
    ]
