# Generated by Django 4.2.7 on 2026-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('qwen', '千问'), ('custom', '自定义')], max_length=30, verbose_name='供应商')),
                ('protocol', models.CharField(choices=[('openai_compatible', 'OpenAI Compatible'), ('gemini', 'Gemini')], default='openai_compatible', max_length=40, verbose_name='协议类型')),
                ('usage', models.CharField(choices=[('general_chat', '通用对话'), ('testcase_writer', '用例生成'), ('testcase_reviewer', '用例评审'), ('automation_agent', '自动化 Agent')], default='general_chat', max_length=40, verbose_name='用途')),
                ('model_name', models.CharField(max_length=120, verbose_name='模型名称')),
                ('base_url', models.URLField(blank=True, max_length=500, verbose_name='Base URL')),
                ('api_key', models.CharField(max_length=800, verbose_name='API Key')),
                ('max_tokens', models.PositiveIntegerField(default=4096, verbose_name='最大输出 Token')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('top_p', models.FloatField(default=1.0, verbose_name='Top P')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'db_table': 'configuration_llm_model_configs',
                'ordering': ['usage', '-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='项目编码')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='负责人')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认项目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
                'db_table': 'configuration_project_configs',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
