# Generated by Django 4.2.7 on 2026-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='provider',
            field=models.CharField(choices=[('chatgpt', 'ChatGPT'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('qwen', '千问')], max_length=30, verbose_name='供应商'),
        ),
    ]
