# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_alter_llmmodelconfig_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="配置名称")),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[("testcase_writer", "测试用例生成"), ("testcase_reviewer", "测试用例评审")],
                        max_length=40,
                        unique=True,
                        verbose_name="提示词类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="提示词内容")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "提示词配置",
                "verbose_name_plural": "提示词配置",
                "db_table": "configuration_prompt_configs",
                "ordering": ["prompt_type"],
            },
        ),
    ]
