# Generated by Codex on 2026-08-03

from django.db import migrations

from apps.configuration.default_prompts import DEFAULT_PROMPT_CONFIGS


def seed_default_prompts(apps, _schema_editor):
    prompt_config = apps.get_model("configuration", "PromptConfig")
    for item in DEFAULT_PROMPT_CONFIGS:
        prompt_config.objects.get_or_create(
            prompt_type=item["prompt_type"],
            defaults={
                "name": item["name"],
                "content": item["content"],
                "is_active": item["is_active"],
            },
        )


def remove_default_prompts(apps, _schema_editor):
    prompt_config = apps.get_model("configuration", "PromptConfig")
    prompt_config.objects.filter(prompt_type__in=[item["prompt_type"] for item in DEFAULT_PROMPT_CONFIGS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0003_promptconfig"),
    ]

    operations = [
        migrations.RunPython(seed_default_prompts, remove_default_prompts),
    ]
