# Generated by Codex on 2026-08-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_seed_default_prompts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promptconfig",
            old_name="prompt_type",
            new_name="role_type",
        ),
        migrations.RenameField(
            model_name="promptconfig",
            old_name="content",
            new_name="prompt_content",
        ),
        migrations.AlterField(
            model_name="promptconfig",
            name="role_type",
            field=models.CharField(
                choices=[("testcase_writer", "测试用例生成专家"), ("testcase_reviewer", "测试用例评审专家")],
                max_length=40,
                verbose_name="系统角色类型",
            ),
        ),
        migrations.AddField(
            model_name="promptconfig",
            name="llm_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_roles",
                to="configuration.llmmodelconfig",
                verbose_name="绑定大模型",
            ),
        ),
        migrations.AlterModelOptions(
            name="promptconfig",
            options={
                "ordering": ["role_type", "-is_active", "-updated_at"],
                "verbose_name": "系统角色配置",
                "verbose_name_plural": "系统角色配置",
            },
        ),
    ]
