# Generated by Django 4.2.7 on 2026-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_requirement_integrator_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodelconfig',
            name='embedding_dimension',
            field=models.PositiveIntegerField(default=768, verbose_name='向量维度'),
        ),
        migrations.AlterField(
            model_name='llmmodelconfig',
            name='usage',
            field=models.CharField(choices=[('general_chat', '通用对话'), ('requirement_integrator', '需求整合'), ('testcase_writer', '用例生成'), ('testcase_reviewer', '用例评审'), ('vision_analyzer', '图片理解'), ('embedding', '文本向量'), ('automation_agent', '自动化 Agent')], default='general_chat', max_length=40, verbose_name='用途'),
        ),
    ]
