# Generated by Django 4.2.7 on 2026-08-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def seed_project_revisions(apps, schema_editor):
    ProjectConfig = apps.get_model('configuration', 'ProjectConfig')
    ProjectConfigRevision = apps.get_model('configuration', 'ProjectConfigRevision')
    for project in ProjectConfig.objects.all().iterator():
        ProjectConfigRevision.objects.create(
            project_id=project.id,
            revision_no=1,
            name=project.name,
            code=project.code,
            description=project.description,
            owner=project.owner,
            project_status=project.status,
            status='confirmed',
            confirmed_at=timezone.now(),
        )


def remove_project_revisions(apps, schema_editor):
    apps.get_model('configuration', 'ProjectConfigRevision').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0009_role_model_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='修订号')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('code', models.SlugField(max_length=80, verbose_name='项目编码')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='负责人')),
                ('project_status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='项目状态')),
                ('status', models.CharField(choices=[('candidate', '待确认'), ('confirmed', '已确认'), ('superseded', '已替代')], default='candidate', max_length=20, verbose_name='修订状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_project_config_revisions', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_config_revisions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='configuration.projectconfigrevision', verbose_name='前一修订')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='configuration.projectconfig', verbose_name='项目')),
            ],
            options={
                'db_table': 'configuration_project_config_revisions',
                'ordering': ['-revision_no', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectconfigrevision',
            constraint=models.UniqueConstraint(fields=('project', 'revision_no'), name='uniq_project_config_revision_no'),
        ),
        migrations.RunPython(seed_project_revisions, remove_project_revisions),
    ]
