# Generated by Django 4.2.7 on 2026-07-31 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_alter_llmmodelconfig_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', '文本'), ('md', 'Markdown'), ('other', '其他')], default='other', max_length=12, verbose_name='文档类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('qiniu_key', models.CharField(max_length=500, unique=True, verbose_name='七牛对象 Key')),
                ('qiniu_url', models.URLField(blank=True, max_length=1000, verbose_name='七牛访问地址')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('parsed', '已解析'), ('failed', '解析失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('parse_message', models.TextField(blank=True, verbose_name='解析信息')),
                ('extracted_text', models.TextField(blank=True, verbose_name='提取文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_documents', to='configuration.projectconfig', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '需求文档',
                'verbose_name_plural': '需求文档',
                'db_table': 'requirement_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_no', models.CharField(max_length=50, verbose_name='需求编号')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('module', models.CharField(max_length=100, verbose_name='功能模块')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='验收标准')),
                ('source_excerpt', models.TextField(blank=True, verbose_name='来源摘录')),
                ('source_locator', models.CharField(blank=True, max_length=200, verbose_name='来源位置')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requirements.requirementdocument', verbose_name='来源文档')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_items', to='configuration.projectconfig', verbose_name='项目')),
            ],
            options={
                'verbose_name': '详细需求',
                'verbose_name_plural': '详细需求',
                'db_table': 'requirement_items',
                'ordering': ['module', 'requirement_no'],
                'unique_together': {('document', 'requirement_no')},
            },
        ),
    ]
