# Generated by Django 4.2.7 on 2026-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocument',
            name='qiniu_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='七牛对象 Key'),
        ),
    ]
