# Generated by Django 4.2.7 on 2026-08-04 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0004_seed_default_prompts'),
        ('requirements', '0002_alter_requirementdocument_qiniu_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='版本名称')),
                ('version_no', models.CharField(max_length=80, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('archived', '归档')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_versions', to='configuration.projectconfig', verbose_name='项目')),
                ('requirement_items', models.ManyToManyField(blank=True, related_name='versions', to='requirements.requirementitem', verbose_name='关联详细需求')),
            ],
            options={
                'verbose_name': '需求版本',
                'verbose_name_plural': '需求版本',
                'db_table': 'requirement_versions',
                'ordering': ['-updated_at', '-id'],
                'unique_together': {('project', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='TestCaseGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '生成中'), ('completed', '已完成'), ('partial_success', '部分成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='需求总数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('generation_log', models.JSONField(blank=True, default=list, verbose_name='生成日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testcase_generation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_generation_tasks', to='configuration.projectconfig', verbose_name='项目')),
                ('requirement_items', models.ManyToManyField(related_name='generation_tasks', to='requirements.requirementitem', verbose_name='待生成详细需求')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_tasks', to='requirements.requirementversion', verbose_name='需求版本')),
            ],
            options={
                'verbose_name': '用例生成任务',
                'verbose_name_plural': '用例生成任务',
                'db_table': 'testcase_generation_tasks',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=80, verbose_name='用例编号')),
                ('title', models.CharField(max_length=300, verbose_name='用例标题')),
                ('preconditions', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.TextField(verbose_name='操作步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('test_type', models.CharField(choices=[('functional', '功能测试'), ('api', '接口测试'), ('ui', '界面测试'), ('integration', '集成测试'), ('performance', '性能测试'), ('security', '安全测试')], default='functional', max_length=20, verbose_name='测试类型')),
                ('status', models.CharField(choices=[('active', '生效'), ('draft', '草稿'), ('deprecated', '废弃')], default='active', max_length=20, verbose_name='状态')),
                ('generated_by_model', models.CharField(blank=True, max_length=120, verbose_name='生成模型')),
                ('reviewed_by_model', models.CharField(blank=True, max_length=120, verbose_name='审核模型')),
                ('review_feedback', models.TextField(blank=True, verbose_name='审核意见')),
                ('raw_content', models.JSONField(blank=True, default=dict, verbose_name='原始内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('generation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='requirements.testcasegenerationtask', verbose_name='生成任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='configuration.projectconfig', verbose_name='项目')),
                ('requirement_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='requirements.requirementitem', verbose_name='详细需求')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='requirements.requirementversion', verbose_name='需求版本')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['-created_at', '-id'],
                'unique_together': {('version', 'requirement_item', 'case_no')},
            },
        ),
    ]
