# Generated by Django 4.2.7 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirements", "0003_requirementversion_testcasegenerationtask_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementdocument",
            name="extracted_blocks",
            field=models.JSONField(blank=True, default=list, verbose_name="结构化内容块"),
        ),
        migrations.AddField(
            model_name="requirementdocument",
            name="extraction_engine",
            field=models.CharField(blank=True, max_length=40, verbose_name="解析引擎"),
        ),
    ]
