# Generated by Django 4.2.7 on 2026-08-05 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirements', '0004_requirementdocument_structured_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', '文本'), ('table', '表格'), ('image', '图片')], max_length=12, verbose_name='内容类型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('text', models.TextField(blank=True, verbose_name='文本内容')),
                ('heading_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='标题层级')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='页码')),
                ('source_locator', models.CharField(blank=True, max_length=255, verbose_name='来源位置')),
                ('table_data', models.JSONField(blank=True, default=dict, verbose_name='表格结构')),
                ('image_key', models.CharField(blank=True, max_length=500, verbose_name='图片对象 Key')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='图片地址')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='图片宽度')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='图片高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'requirement_content_blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementParseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_no', models.PositiveIntegerField(verbose_name='解析批次')),
                ('status', models.CharField(choices=[('processing', '解析中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=20, verbose_name='状态')),
                ('extraction_engine', models.CharField(blank=True, max_length=40, verbose_name='解析引擎')),
                ('message', models.TextField(blank=True, verbose_name='解析信息')),
                ('block_count', models.PositiveIntegerField(default=0, verbose_name='内容块数')),
                ('requirement_count', models.PositiveIntegerField(default=0, verbose_name='需求数')),
                ('table_count', models.PositiveIntegerField(default=0, verbose_name='表格数')),
                ('image_count', models.PositiveIntegerField(default=0, verbose_name='图片数')),
                ('filtered_count', models.PositiveIntegerField(default=0, verbose_name='过滤块数')),
                ('filtered_blocks', models.JSONField(blank=True, default=list, verbose_name='过滤记录')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前批次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'db_table': 'requirement_parse_runs',
                'ordering': ['-run_no', '-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='requirementitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='已归档'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='当前有效'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='merged_from',
            field=models.ManyToManyField(blank=True, related_name='merged_into', to='requirements.requirementitem', verbose_name='合并来源'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='supplementary_description',
            field=models.TextField(blank=True, verbose_name='补充描述'),
        ),
        migrations.AddField(
            model_name='requirementparserun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_parse_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='requirementparserun',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_runs', to='requirements.requirementdocument', verbose_name='来源文档'),
        ),
        migrations.AddField(
            model_name='requirementcontentblock',
            name='parse_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='requirements.requirementparserun', verbose_name='解析批次'),
        ),
        migrations.AddField(
            model_name='requirementcontentblock',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='requirements.requirementitem', verbose_name='所属需求'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='parse_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='requirements.requirementparserun', verbose_name='解析批次'),
        ),
        migrations.AddConstraint(
            model_name='requirementitem',
            constraint=models.UniqueConstraint(fields=('document', 'parse_run', 'requirement_no'), name='uniq_parse_run_requirement_no'),
        ),
        migrations.AddConstraint(
            model_name='requirementparserun',
            constraint=models.UniqueConstraint(fields=('document', 'run_no'), name='uniq_document_parse_run'),
        ),
    ]
