# Generated by Django 4.2.7 on 2026-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_normalize_qiniu_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirementitem',
            name='source_excerpt',
        ),
        migrations.RemoveField(
            model_name='requirementitem',
            name='source_locator',
        ),
    ]
