# Generated by Django 4.2.7 on 2026-08-11 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_version_lifecycle(apps, schema_editor):
    RequirementVersion = apps.get_model('requirements', 'RequirementVersion')
    project_ids = RequirementVersion.objects.values_list('project_id', flat=True).distinct()
    for project_id in project_ids:
        versions = RequirementVersion.objects.filter(project_id=project_id).order_by('created_at', 'id')
        for sequence, version in enumerate(versions, start=1):
            old_status = version.status
            version.sequence = sequence
            if old_status == 'active':
                version.status = 'published'
            elif old_status not in {'draft', 'published', 'archived'}:
                version.status = 'archived'
            version.save(update_fields=['sequence', 'status'])


def reverse_version_lifecycle(apps, schema_editor):
    RequirementVersion = apps.get_model('requirements', 'RequirementVersion')
    RequirementVersion.objects.filter(status='published').update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0008_llmmodelconfig_embedding_dimension_and_more'),
        ('project_knowledge', '0001_initial'),
        ('requirements', '0012_requirementintegrationdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_statement', models.TextField()),
                ('historical_statement', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已解决')], default='pending', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('current', '采用当前规则'), ('historical', '保留历史规则'), ('manual', '手工规则')], max_length=20)),
                ('final_statement', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_conflicts',
            },
        ),
        migrations.CreateModel(
            name='RequirementFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_no', models.CharField(max_length=80, verbose_name='需求族编号')),
                ('title', models.CharField(max_length=200, verbose_name='需求族标题')),
                ('status', models.CharField(choices=[('active', '有效'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'requirement_families',
                'ordering': ['family_no'],
            },
        ),
        migrations.CreateModel(
            name='RequirementIntegrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('partial_success', '部分成功'), ('failed', '失败')], default='pending', max_length=24, verbose_name='状态')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_integration_batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementIntegrationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('fact', '当前事实'), ('inherited', '继承规则'), ('change', '变更'), ('conflict', '冲突'), ('coverage', '覆盖提示')], max_length=20, verbose_name='用途')),
                ('asset_type', models.CharField(max_length=40, verbose_name='资产类型')),
                ('asset_id', models.PositiveBigIntegerField(verbose_name='资产ID')),
                ('asset_revision_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chunk_id', models.CharField(blank=True, max_length=160)),
                ('source_locator', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(verbose_name='证据快照')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'requirement_integration_evidence',
            },
        ),
        migrations.CreateModel(
            name='RequirementIntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('source_content_hash', models.CharField(max_length=64, verbose_name='原文哈希')),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_name', models.CharField(blank=True, max_length=120)),
                ('search_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_integration_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('vector_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rrf_rank', models.PositiveIntegerField(verbose_name='融合排名')),
                ('matched_excerpt', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'requirement_match_candidates',
            },
        ),
        migrations.CreateModel(
            name='RequirementOpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=40)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('open', '待回答'), ('answered', '已回答'), ('not_applicable', '不适用'), ('accepted_warning', '接受警告')], default='open', max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_open_questions',
            },
        ),
        migrations.CreateModel(
            name='RequirementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField(verbose_name='修订号')),
                ('change_type', models.CharField(choices=[('initial', '新增'), ('continued', '延续'), ('modified', '修改'), ('deprecated', '废弃')], max_length=20, verbose_name='变更类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='验收标准')),
                ('supplementary_description', models.TextField(blank=True, verbose_name='补充描述')),
                ('source_summary', models.TextField(blank=True, verbose_name='来源摘要')),
                ('source_content_hash', models.CharField(max_length=64, verbose_name='原文哈希')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='确认时间')),
            ],
            options={
                'db_table': 'requirement_revisions',
                'ordering': ['family', 'revision_no'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='requirementversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='requirementdocument',
            name='target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='requirements.requirementversion', verbose_name='目标版本'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='change_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='变更类型'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='formal_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_drafts', to='project_knowledge.projectmodule', verbose_name='正式模块'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='relationship_confirmed',
            field=models.BooleanField(default=False, verbose_name='关系已确认'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='relationship_mode',
            field=models.CharField(blank=True, max_length=20, verbose_name='关系模式'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='review_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_requirement_integration_drafts', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='source_content_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='原文哈希'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_drafts', to='requirements.requirementversion', verbose_name='目标版本'),
        ),
        migrations.AddField(
            model_name='requirementitem',
            name='formal_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirement_items', to='project_knowledge.projectmodule', verbose_name='正式模块'),
        ),
        migrations.AddField(
            model_name='requirementversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='requirementversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_requirement_versions', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='requirementversion',
            name='sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='版本顺序'),
        ),
        migrations.AlterField(
            model_name='requirementdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('parsed', '已解析'), ('failed', '解析失败'), ('archived', '已归档')], default='uploaded', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='requirementversion',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.RunPython(backfill_version_lifecycle, reverse_version_lifecycle),
        migrations.AddConstraint(
            model_name='requirementversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_no'), name='uniq_project_version_no'),
        ),
        migrations.AddConstraint(
            model_name='requirementversion',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='uniq_project_version_sequence'),
        ),
        migrations.AddField(
            model_name='requirementrevision',
            name='confirmed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_requirement_revisions', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='requirementrevision',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='requirements.requirementfamily', verbose_name='需求族'),
        ),
        migrations.AddField(
            model_name='requirementrevision',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_revisions', to='project_knowledge.projectmodule', verbose_name='正式模块'),
        ),
        migrations.AddField(
            model_name='requirementrevision',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revisions', to='requirements.requirementrevision', verbose_name='前一修订'),
        ),
        migrations.AddField(
            model_name='requirementrevision',
            name='source_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formal_revision', to='requirements.requirementitem', verbose_name='来源候选需求'),
        ),
        migrations.AddField(
            model_name='requirementopenquestion',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_requirement_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementopenquestion',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='requirements.requirementintegrationrun', verbose_name='整合运行'),
        ),
        migrations.AddField(
            model_name='requirementmatchcandidate',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_candidates', to='requirements.requirementrevision', verbose_name='候选修订'),
        ),
        migrations.AddField(
            model_name='requirementmatchcandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='requirements.requirementintegrationrun', verbose_name='整合运行'),
        ),
        migrations.AddField(
            model_name='requirementintegrationrun',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='requirements.requirementintegrationbatch', verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='requirementintegrationrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_integration_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AddField(
            model_name='requirementintegrationrun',
            name='requirement_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_runs', to='requirements.requirementitem', verbose_name='候选需求'),
        ),
        migrations.AddField(
            model_name='requirementintegrationrun',
            name='target_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_runs', to='requirements.requirementversion', verbose_name='目标版本'),
        ),
        migrations.AddField(
            model_name='requirementintegrationevidence',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='requirements.requirementintegrationrun', verbose_name='整合运行'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_integration_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_batches', to='requirements.requirementdocument', verbose_name='来源文档'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_integration_batches', to='configuration.projectconfig', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='requirement_items',
            field=models.ManyToManyField(related_name='integration_batches', to='requirements.requirementitem', verbose_name='候选需求'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='target_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_batches', to='requirements.requirementversion', verbose_name='目标版本'),
        ),
        migrations.AddField(
            model_name='requirementfamily',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requirement_families', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='requirementfamily',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_families', to='project_knowledge.projectmodule', verbose_name='正式模块'),
        ),
        migrations.AddField(
            model_name='requirementfamily',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_families', to='configuration.projectconfig', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='requirementconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_requirement_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementconflict',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='requirements.requirementintegrationrun', verbose_name='整合运行'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='selected_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_drafts', to='requirements.requirementfamily', verbose_name='选定需求族'),
        ),
        migrations.AddField(
            model_name='requirementversion',
            name='requirement_revisions',
            field=models.ManyToManyField(blank=True, related_name='versions', to='requirements.requirementrevision', verbose_name='正式需求修订'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='requirement_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='requirements.requirementrevision', verbose_name='正式需求修订'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_revisions',
            field=models.ManyToManyField(blank=True, related_name='generation_tasks', to='requirements.requirementrevision', verbose_name='待生成正式需求'),
        ),
        migrations.AddConstraint(
            model_name='requirementrevision',
            constraint=models.UniqueConstraint(fields=('family', 'revision_no'), name='uniq_family_revision_no'),
        ),
        migrations.AddConstraint(
            model_name='requirementmatchcandidate',
            constraint=models.UniqueConstraint(fields=('run', 'revision'), name='uniq_run_match_revision'),
        ),
        migrations.AddConstraint(
            model_name='requirementfamily',
            constraint=models.UniqueConstraint(fields=('project', 'family_no'), name='uniq_project_family_no'),
        ),
    ]
