# Generated by Django 4.2.7 on 2026-08-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0019_testcase_enhancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementimageanalysis',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='requirementintegrationbatch',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='requirements.requirementintegrationbatch', verbose_name='重试来源'),
        ),
        migrations.AddField(
            model_name='requirementintegrationdraft',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='requirementintegrationrun',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='requirementparserun',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='requirementparserun',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='requirements.requirementparserun', verbose_name='重试来源'),
        ),
        migrations.AddField(
            model_name='testcaseenhancementtask',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='testcaseenhancementtask',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='requirements.testcaseenhancementtask', verbose_name='重试来源'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='error_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化错误'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='requirements.testcasegenerationtask', verbose_name='重试来源'),
        ),
    ]
